# Site settings
title: WinOrLearn
description: "Junior developer 양찬우 개발 블로그"
url: "https://oizys18.github.io/"
baseurl: "https://oizys18.github.io/"
# Google Analytics
google_analytics: UA-153492714-1

# Author
author:
  name: 양찬우
  url: https://oizys18.github.io
  email: oizys18@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages
  - _posts

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc
  - jemoji

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# Disqus (Set to your disqus id)
disqus: https-oizys18-github-io

# Default 세팅
defaults:
  - scope:
      path: "" # 이 빈 문자열은 프로젝트의 모든 파일을 의미함
      type: "posts" # 이전 Jekyll 2.2 에서는 `post`
    values:
      comments: true
      toc: true
      toc_sticky: true

# Table of contents 세팅
toc:
  min_level: 1 # default: 1
  max_level: 3 # default: 6
  list_class: section-nav
  item_class: toc-entry
  item_prefix: toc-
  sublist_class: "sublist"
